#!/bin/bash

# Create home directories
mkdir -p ~/Pictures ~/Music ~/Downloads ~/Videos ~/Documents

# Install ZSH as the default shell
sudo chmod +x installScripts/installZsh && ./installScripts/installZsh

# Install st
sudo chmod +x installScripts/installSt && ./installScripts/installSt

# Install dmenu
sudo chmod +x installScripts/installDmenu && ./installScripts/installDmenu

# Move to config folder
cd config

# Copy config files for i3
cp -r ./i3 ~/.config
cp -r ./i3status ~/.config
cp -r ./dunst ~/.config
cp -r ./mpd ~/.config
cp -r ./ncmpcpp ~/.config
cp .vimrc ~/
sudo cp i3exit /usr/bin

# Copy Ly config file
sudo cp ./ly/config.ini /etc/ly/

# Configure touchpad
sudo mkdir -p /etc/X11/xorg.conf.d
sudo cp ./config/30-touchpad.conf /etc/X11/xorg.conf.d/

# Copy .Xresources for color scheme
cp .Xresources ~/ && xrdb -merge ~/.Xresources

# Move back to previous folder
cd ..

# Copy custom scripts
mkdir -p ~/.local/ && cp -R ./bin ~/.local/
sudo chmod +x ~/.local/bin/*

# Copy wallpapers
cp -R ./wallpapers ~/Pictures

# Reduce grub timeout to 0
sudo sed -i "s/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g" /etc/default/grub

# Clean up system
./bin/pacm

# Reboot the system
sudo reboot
