#!/bin/bash

# Create home directories
cd /home/akshay/
mkdir -p Pictures Music Downloads Videos Documents

# Install ZSH as the default shell
cd Arch-i3-Dotfiles
sudo chmod +x installScripts/installZsh && ./installScripts/installZsh

# Install st
sudo chmod +x installScripts/installSt && ./installScripts/installSt

# Install dmenu
sudo chmod +x installScripts/installDmenu && ./installScripts/installDmenu

# Move to config folder
cd config

# Copy config files for i3
cp -r ./i3 /home/akshay/.config
cp -r ./i3status /home/akshay/.config
cp -r ./dunst /home/akshay/.config
cp -r ./mpd /home/akshay/.config
cp -r ./ncmpcpp /home/akshay/.config
cp .vimrc /home/akshay/
sudo cp i3exit /usr/bin

# Copy Ly config file
sudo cp ./ly/config.ini /etc/ly/

# Configure touchpad
sudo mkdir -p /etc/X11/xorg.conf.d
sudo cp ./30-touchpad.conf /etc/X11/xorg.conf.d/

# Move back to previous folder
cd ..

# Copy custom scripts
mkdir -p ~/.local/ && cp -R ./bin ~/.local/
sudo chmod +x ~/.local/bin/*

# Reduce grub timeout to 0
sudo sed -i "s/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g" /etc/default/grub

# Move to home folder
cd /home/akshay/

# Copy wallpapers
cp -R Arch-i3-Dotfiles/wallpapers Pictures/

# Copy .Xresources for color scheme
cp Arch-i3-Dotfiles/config/.Xresources . && xrdb -merge .Xresources

# Configure vim
mkdir -p .vim && cd .vim
mkdir -p autoload bundle && \
curl -LSso autoload/pathogen.vim https://tpo.pe/pathogen.vim
cd bundle/
git clone https://github.com/jiangmiao/auto-pairs.git
git clone https://github.com/vim-scripts/AutoComplPop.git
git clone https://github.com/joshdick/onedark.vim.git
git clone https://github.com/vim-scripts/SearchComplete.git

# Clean up system
./bin/pacm

# Reboot the system
sudo reboot
