#!/bin/bash
        
# Configure locale
vim /etc/locale.gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
export LANG=en_US.UTF-8

# Configure grub
grub-install --recheck --target=i386-pc /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

# Configure pacman
vim /etc/pacman.conf # uncomment multilib
pacman -Syy

# Configure users
EDITOR=vim visudo # uncomment %wheel ALL=(ALL) ALL
useradd -m -g users -G wheel,storage,power -s /bin/bash akshay
passwd akshay # enter user password
passwd # enter root password

# Install Ly as the login manager
sudo chmod +x installScripts/installLy && ./installScripts/installLy

# Enable NetworkManager service
systemctl enable NetworkManager

